chore(ci): temporary fix cache

diff --git a/.github/actions/run-codegen/action.yaml b/.github/actions/run-codegen/action.yaml
--- a/.github/actions/run-codegen/action.yaml
+++ b/.github/actions/run-codegen/action.yaml
@@ -64,6 +64,27 @@ runs:
         GH_TOKEN: ${{ github.token }}
       continue-on-error: true
 
+    - name: Clean Cargo Registry
+      run: |
+        CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
+        printf "Cleaning ~/.cargo before saving\n"
+        cargo cache --autoclean
+        index_dir="$CARGO_HOME/registry/index"
+        if [[ -d "$index_dir" ]]; then
+          find "$index_dir" -type d -name ".git" -execdir rm -rf {} \;
+        fi
+
+    - name: Clean Target Profile
+      run: |
+        WORKSPACE_ROOT="${GITHUB_WORKSPACE:-$PWD}"
+        target_profile=$(jq -r '.target_profile' < config.json) || { printf "Error reading target profile from config.json\n" >&2; exit 1; }
+        printf "Cleaning target/%s before saving\n" "$target_profile"
+        target_dir="$WORKSPACE_ROOT/target/$target_profile"
+        printf "Removing examples and incremental directories\n"
+        find "$target_dir" -type d \( -name "examples" -o -name "incremental" \) -exec rm -rf {} \;
+        printf "Removing dep-info files (*.d)\n"
+        find "$target_dir" -type f -name "*.d" -exec rm -f {} \;
+
     - name: Save new rust cache
       uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
       with:
